language: node_js
on: [push]

addons:
  chrome: stable

node_js:
  - "10"

before_install:
- npm install -g @lhci/cli

services:
  - xvfb

install:
  - npm install

script:
  - npm run build
  - npm run test:ci

after_success:
  - cat ./static/tamu-library-components/reports/coverage/tamu-library-components/lcov.info | ./node_modules/coveralls/bin/coveralls.js,
  - npm run build:static-production

notifications:
  webhooks:
    urls:
      - https://coveralls.io/webhook

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: sprint9-staging-test
