language: node_js
name: TEST TRAVIS CI
on: [push]

addons:
  chrome: stable

node_js:
  - "10"

services:
  - xvfb

install:
  - npm install

script:
  - npm run build
  - npm run test:ci
  - lhci autorun --upload.target=temporary-public-storage --config=./lighthouserc.json
  - node scripts/build-tl-components-lighthouse-badges.js

after_success:
  - cat ./static/tamu-library-components/reports/coverage/tamu-library-components/lcov.info | ./node_modules/coveralls/bin/coveralls.js,
  - npm run build:static-production

notifications:
  webhooks:
    urls:
      - https://coveralls.io/webhook

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
