#!/bin/bash

set -e

versionLocation=/usr/local/apache2/htdocs/tl-components/1x/config.json
latestLocation=/usr/local/apache2/htdocs/tl-components/latest/config.json

eval "cat << EOF | tee $versionLocation $latestLocation
$(<tmp/config-template.json)
EOF"

echo "Done docker-entrypoint..."

exec "$@"
